Travel_Buddy/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

urlpatterns = [
	url(r'^', include('apps.login.urls')),
    url(r'^users/', include('apps.login.urls', namespace = 'users')),
    url(r'^travel/', include('apps.travel.urls', namespace = 'travel')),
]

apps/login/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^register$', views.register, name = 'register'),
    url(r'^success$', views.success, name = 'success'),
    url(r'^login$', views.login, name = 'login'),
    url(r'^logout$', views.logout, name = 'logout')
]

apps/travel/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^info/(?P<id>\d+)$', views.info, name = 'info'),
    url(r'^create$', views.create, name = 'create'),
    url(r'^add$', views.add, name = 'add'),
    url(r'^join/(?P<id>\d+)$', views.join, name = 'join'),
    url(r'^remove/(?P<id>\d+)$', views.remove, name = 'remove'),
    url(r'^delete/(?P<id>\d+)$', views.delete, name = 'delete'),
]

apps/login/models.py
from __future__ import unicode_literals
from django.db import models
from dateutil.parser import parse as parse_date
import re, bcrypt, datetime
from datetime import date


# Create your models here.
class UserManager(models.Manager):
	def register_user(self, postData):
		errors = []

		# 1. run our validations
		if len(postData['name']) < 2:
			errors.append('Name must be 2 characters or more!')
		if len(postData['username']) < 2:
			errors.append('Username must be 2 characters or more!')
		if self.filter(username = postData['username']):
			errors.append("This username has already been registered!")
		if len(postData['password']) < 8:
			errors.append('Password must be at least 8 characters long!')
		if not postData['password'] == postData['confirm_password']:
			errors.append('Password must match!')
	
		response_to_views = {}
		# 2. check if validations are true or false
		# 2a. if true
		if not errors:
			# create user
			hashed_password = bcrypt.hashpw(postData['password'].encode(), bcrypt.gensalt())
			user = self.create(name = postData['name'], username = postData['username'], password = hashed_password)
			
			response_to_views['user'] = user
			response_to_views['status'] = True
			response_to_views['confirm'] = ['You just successfully registered!']
				# send a resonse to views (user, true)
			# 2b. if false
		else:
			# send a response to views (errors, false)
			response_to_views['user'] = errors
			response_to_views['status'] = False
		# send response to the views
		return response_to_views

	def login_user(self, postData):
		errors = []
		response_to_views = {}
		# find a user with username for PostData
		user = self.filter(username = postData['username'])
		response_to_views['user'] = user
		# if not user
		if not user:
			# send errors to views
			response_to_views['status'] = False
			errors.append('Username not found!')
			response_to_views['user'] = errors
		# else
		else:
			# check passwords from postData to hashed_password from db
			if bcrypt.checkpw(postData['password'].encode(), user[0].password.encode()): #encode all password before sending and/or checking
			# if true
				response_to_views['status'] = True
				response_to_views['user'] = user.first()
				response_to_views['confirm'] = ['You have successfully logged in!']
				# send user to sucess.views, true

			# if false
			else:
				# send errors to views, false
				response_to_views['status'] = False
				errors.append('Invalid Username/Password combination!')
				response_to_views['user'] = errors
		return response_to_views

class User(models.Model):
	name = models.CharField(max_length = 55)
	username = models.CharField(max_length = 55)
	password = models.CharField(max_length = 255)
	created_at = models.DateTimeField(auto_now_add = True)
	updated_at = models.DateTimeField(auto_now = True)


	objects = UserManager()

apps/login/views.py
from django.shortcuts import render, redirect, HttpResponse
from .models import User
from ..travel.models import Trip
from django.contrib import messages
# Create your views here.

def index(request):

	return render(request, 'login/index.html')

def register(request):
	# invoke the method from models and capture the response
	response_from_models = User.objects.register_user(request.POST)
	# check to see if response is true
	if response_from_models['status']:
		# save user_id in session
		request.session['user_id'] = response_from_models['user'].id
		request.session['user_name'] = response_from_models['user'].name
		request.session['user_username'] = response_from_models['user'].username
		# Successfull register message
		for confirm in response_from_models['confirm']:
			messages.error(request, confirm)
		# redirect to success page
		return redirect('users:success')
	# else
	else:
		# send the error messages to client
		for error in response_from_models['user']:
			messages.error(request, error)
		# redirect to index page
		return redirect('users:index')

def login(request):
		# invoke the method from models and capture the response
	response_from_models = User.objects.login_user(request.POST)
	# check to see if response is true
	if response_from_models['status']:
		# save user_id in session
		request.session['user_id'] = response_from_models['user'].id
		request.session['user_name'] = response_from_models['user'].name
		request.session['user_username'] = response_from_models['user'].username
		# Successfull Login message
		for confirm in response_from_models['confirm']:
			messages.error(request, confirm)
		# redirect to success page
		return redirect('users:success')
	# else
	else:
		# send the error messages to client
		for error in response_from_models['user']:
			messages.error(request, error)
		# redirect to index page
		return redirect('users:index')

def success(request):
	if 'user_id' in request.session:

		context = {
			'items_list': Trip.objects.exclude(all_lists = request.session['user_id']).order_by('from_date'),
			'my_list': Trip.objects.filter(all_lists = request.session['user_id']).order_by('from_date'),
		}

		return render(request, 'login/success.html', context)
	else:
		return redirect('users:index')
def logout(request):
	request.session.clear()
	return redirect('users:index')

apps/login/templates/login/index.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Login/Registration</title>
</head>
<body>
	<div class="register">
		{% if messages %}
			{% for message in messages %}
				<p>{{message}}</p>
			{% endfor %}
		{% endif %}

		<h1>Registration</h1>
		<form class="" action="{% url 'users:register' %}" method="POST">
			{% csrf_token %}
			<table>
				<tr>
					<td>Name: </td>
					<td><input type="text" name="name" value=""></td>
				</tr>
				<tr>
					<td>Username: </td>
					<td><input type="text" name="username" value=""></td>
				</tr>
				<tr>
					<td>Password: </td>
					<td><input type="password" name="password" value="password"></td>
				</tr>
				<tr>
					<td>Confirm Password: </td>
					<td><input type="password" name="confirm_password" value="password"></td>
				</tr>
				<tr>
					<td></td>
					<td><input type="submit" name="" value="Register"></td>
				</tr>
			</table>
			<p>*Password must be at least 8 characters log</p>
		</form>
	</div>
	<div class="login">
		<h1>Login</h1>
		<form class="" action="{% url 'users:login' %}" method="POST">
			{% csrf_token %}
			<table>
				<tr>
					<td>Username: </td>
					<td><input type="text" name="username" value=""></td>
				</tr>
				<tr><td>Password: </td>
					<td><input type="password" name="password" value="password"></td></tr>
				<tr>
					</td>
					<td><input type="submit" name="" value="Login"></td>
				</tr>
			</table>
			
		</form>
	</div>
</body>
</html>

apps/login/templates/login/success.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>My Wish List</title>
		<style type="text/css">
		
			.success {
				border: 1px solid black;
				background-color: green;
				width: 300px;
				color: white;
			}
			form {
				display: inline;
			}
			.row1 {
				background-color: #D3D3D3;
			}
			.head_row {
				background: pink;
			}
			table {
				border: 1px solid black;
			}

		</style>
	</head>
	<body>
		<h1>Hello, {{ request.session.user_name }}!</h1>
		<!-- log out function -->
		<p><a href="{% url 'users:logout' %}">Logout</a></p>

		

<!-- This link is to be removed -->
	
		<!-- Flash Messages -->
		{% if messages %}
			{% for message in messages %}
				<p class="success">{{message}}</p>
			{% endfor %}
		{% endif %}
		
		<!-- Your travel -->
		<h2>Your Trip Schedules:</h2>
		<table>
			<thead>
				<tr class="head_row">
					<th>Destination</th>
					<th>Travel Start Date</th>
					<th>Travel End Date</th>
					<th>Plan</th>
					<th>Action</th>
				</tr>
			</thead>
				{% for item in my_list %}
				<tr class="{% cycle 'row1' 'row2' %}">			
					<td><a href="{% url 'travel:info' item.id %}">{{item.destination}}</a></td>
					<td>{{item.from_date}}</td>
					<td>{{item.to_date}}</td>
					<td>{{item.description}}</td>
					<td>
						<form class="remove_from_list" action="{% url 'travel:remove' item.id %}" method="POST">
							{% csrf_token %}
						<input type="submit" name="remove" value="Remove Trip">
						</form>
						{% if item.creator.id == request.session.user_id %}
						<form class="delete" action="{% url 'travel:delete' item.id %}" method="POST">
							{% csrf_token %}
						<input type="submit" name="delete" value="Delete">
						</form>
						{% endif %}
					</td>
				</tr>
				{% endfor %}
			</table>

		<!-- Other's Wishlist -->
		<h2>Other Users' Travel Plans</h2>
			<table>
				<thead>
					<tr class="head_row">
						<th>Name</th>
						<th>Destination</th>
						<th>Travel Start Date</th>
						<th>Travel End Date</th>
						<th>Do You Want To Join?</th>
					</tr>
				</thead>
				{% for item in items_list %}
				<tr class="{% cycle 'row1' 'row2' %}">	
					<td>{{item.creator.name}}</td>		
					<td><a href="{% url 'travel:info' item.id %}">{{item.destination}}</a></td>
					<td>{{item.from_date}}</td>
					<td>{{item.to_date}}</td>
					<td class="buttons">
						<form class="add_to_list" action="{% url 'travel:join' item.id %}" method="POST">
							{% csrf_token %}
						<input type="submit" name="join" value="Join">
						</form>
						{% if item.creator.id == request.session.user_id %}
						<form class="delete" action="{% url 'travel:delete' item.id %}" method="POST">
							{% csrf_token %}
						<input type="submit" name="delete" value="Delete">
						</form>
						{% endif %}
					</td>
				</tr>
				{% endfor %}
			</table>
		<!-- Add Trip Button -->
		<a href="{% url 'travel:create' %}">Add Travel Plan</a>
		
	</body>
</html>