Travel_Buddy/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

urlpatterns = [
	url(r'^', include('apps.login.urls')),
    url(r'^users/', include('apps.login.urls', namespace = 'users')),
    url(r'^travel/', include('apps.travel.urls', namespace = 'travel')),
]

apps/login/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^register$', views.register, name = 'register'),
    url(r'^success$', views.success, name = 'success'),
    url(r'^login$', views.login, name = 'login'),
    url(r'^logout$', views.logout, name = 'logout')
]

apps/travel/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^info/(?P<id>\d+)$', views.info, name = 'info'),
    url(r'^create$', views.create, name = 'create'),
    url(r'^add$', views.add, name = 'add'),
    url(r'^join/(?P<id>\d+)$', views.join, name = 'join'),
    url(r'^remove/(?P<id>\d+)$', views.remove, name = 'remove'),
    url(r'^delete/(?P<id>\d+)$', views.delete, name = 'delete'),
]

apps/travel/models.py
from __future__ import unicode_literals
from django.db import models
from ..login.models import User
import datetime

# Create your models here.

class TripManager(models.Manager):

	def add_trip(self, postData, id):
		errors = []

		destination = postData['destination']
		description = postData['description']
		from_date = postData['from_date']
		to_date = postData['to_date']
		creator = id

		# run validations:
		if len(destination) < 1:
			errors.append('Destination CANNOT be blank!')
		if len(description) < 1:
			errors.append('Description CANNOT be blank!')
		if from_date == '':
			errors.append('Travel Date From field CANNOT be blank!')
		else:	
			from_date = datetime.datetime.strptime(from_date, "%Y-%m-%d").date()
			if from_date < datetime.date.today():
					errors.append("Travel Date From field CANNOT be prior to today's date")
		if to_date == '':
			errors.append('Travel Date To field CANNOT be blank!')
		else:	
			to_date = datetime.datetime.strptime(to_date, "%Y-%m-%d").date()
			if to_date < from_date:
					errors.append("Travel Date To field CANNOT be prior to today's date")

		# If all validations pass
		response_to_views = {}

		if not errors:
			trip = Trip.objects.create(destination = destination, description = description, from_date = from_date, to_date = to_date, creator = creator)

			trip.all_lists.add(creator)
			
			# send a response to views (trip, true)
			response_to_views['trip'] = trip
			response_to_views['status'] = True

		else:
			#send a response to views (errors, false)
			response_to_views['trip'] = errors
			response_to_views['status'] = False

		return response_to_views



class Trip(models.Model):

	destination = models.CharField(max_length = 100)
	description = models.TextField(max_length = 1000)
	from_date = models.DateField(auto_now = False)
	to_date = models.DateField(auto_now = False)
	creator = models.ForeignKey(User, related_name = "trip_creator")
	all_lists = models.ManyToManyField(User, related_name = "all_trips")
	created_at = models.DateTimeField(auto_now_add = True)
	updated_at = models.DateTimeField(auto_now = True) 

	objects = TripManager()

apps/travel/views.py
from django.shortcuts import render, redirect, HttpResponse
from .models import Trip
from ..login.models import User
from django.contrib import messages
import datetime 


def index(request):
	pass

def info(request, id):
	if 'user_id' in request.session:

		context = {
			'items_list': Trip.objects.filter(id = id),
		}
		return render(request, 'travel/info.html', context)
	else:
		return redirect('users:index')

def create(request):
	if 'user_id' in request.session:
		return render(request, 'travel/add.html')
	else:
		return redirect('users:index')

def add(request):
	if 'user_id' in request.session:
		if request.method == 'POST':
			user = User.objects.get(id = request.session['user_id'])
			response_from_models = Trip.objects.add_trip(request.POST, user)

			if response_from_models['status']:
	
				return redirect('users:success')

			else:
				for error in response_from_models['trip']:
					messages.error(request, error)

					return redirect('travel:create')
	else:
		return redirect('users:index')

def join(request, id):
	if 'user_id' in request.session:
		# Add item to my travel list
		user = User.objects.get(id = request.session['user_id'])
		trip = Trip.objects.get(id = id)
		trip.all_lists.add(user)

		return redirect('users:success')
	else:
		return redirect('users:index')

def remove(request, id):
	if 'user_id' in request.session:
		# Remove item from my travel list
		user = User.objects.get(id = request.session['user_id'])
		trip = Trip.objects.get(id = id)
		trip.all_lists.remove(user)

		return redirect('users:success')
	else:
		return redirect('users:index')
def delete(request, id):
	if 'user_id' in request.session:
		# Delete the trip
		Trip.objects.get(id = id).delete()

		return redirect('users:success')
	else:
		return redirect('users:index')

apps/travel/templates/travel/add.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Add Plan</title>
	</head>
	<body>
		<!-- Home / Logout link -->
		<p><a href="{% url 'users:success' %}">Home</a> | <a href="{% url 'users:logout' %}">Logout</a></p>

		<!-- Flash Messages -->
		{% if messages %}
			{% for message in messages %}
				<p class="success">{{message}}</p>
			{% endfor %}
		{% endif %}

		<!-- Form for creating a new wish list item -->
		<h1>Add a Trip</h1>
		<form class="add_item" action="{% url 'travel:add' %}" method="POST">
			{% csrf_token %}
			<table>
				<tr>
					<td><label>Destination:</label></td>
					<td><input type="text" name="destination"></td>
				</tr>
				<tr>
					<td><label>Description:</label></td>
					<td><input type="text" name="description"></td>
				</tr>
			</table>
			<table>
				<tr>
					<td><label>Travel Date From:</label></td>
					<td><input type="date" name="from_date"></td>
				</tr>
				<tr>
					<td><label>Travel Date To:</label></td>
					<td><input type="date" name="to_date"></td>
				</tr>
			</table>
				
			<input type="submit" name="add" value="Add">
				
			
		</form>
	</body>
</html>

apps/travel/templates/travel/info.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		{% for item in items_list %}
		<title>{{ item.product }}</title>
		{% endfor %}
		<style type="text/css">
			.row1 {
				background-color: #D3D3D3;
			}
			.head_row {
				background: pink;
			}
			table {
				border: 1px solid black;
			}
			h1 {
				color: blue;
			}
			h2 {
				color: #228B22;
			}
		</style>
	</head>
	<body>

		<!-- Home / Logout link -->
		<p><a href="{% url 'users:success' %}">Home</a> | <a href="{% url 'users:logout' %}">Logout</a></p>

		<!-- Flash Messages -->
		{% if messages %}
			{% for message in messages %}
				<p>{{message}}</p>
			{% endfor %}
		{% endif %}

		<!-- Item name and information -->
		{% for item in items_list %}
		<h1>{{ item.destination }}</h1>
			<ul>
				<li>Planned By: {{item.creator.name}}</li>
				<li>Description: {{item.description}}</li>
				<li>Travel Date From: {{item.from_date}}</li>
				<li>Travel Date To: {{item.to_date}}</li>
			</ul>
		
		

		<!-- Other users joining this trip -->
		<h3>Other users joining the trip:</h3>
			<table>
				<tr class="head_row">
					<th>Name</th>
				</tr>
				{% for x in item.all_lists.all %}
				<tr class="{% cycle 'row1' 'row2' %}">
					<td>{{x.name}}</td>
				</tr>
				{% endfor %}
			</table>				
		
		{% endfor %}
	</body>
</html>